version: '3.4'

services:
  cleanarchitecture.db:
    image: postgres:16.0
  cleanarchitecture.api:
    image: ${DOCKER_REGISTRY-}cleanarchitectureapi
    build:
      context: .
      dockerfile: src/CleanArchitecture/CleanArchitecture.Api/Dockerfile
